# num = int(input())
# arr = []
# for i in input().split():
#     arr.append(int (i))
# val = int(input())
# arr.append(val)
# pos,v = input().split()
# pos = int(pos)
# v = int(v)
# arr.insert(pos,v)
# arr.reverse()
# arr.sort()
# arr.sort(reverse=True)
# # print(arr.index(arr[4]))
# # arr.extend()
# # print(arr)
# rem = int(input())
# arr.remove(rem)
# arr.pop()
# arr.reverse()
# print(arr)    